targets:
  $default:
    builders:
      drift_dev:
        options:
          case_from_dart_to_sql: camelCase
      hive_generator:
        options:
          runs_before:
            - auto_route_generator
